-- MySQL Script generated by MySQL Workbench
-- Fri Jun 13 15:54:58 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema reaktor_bookingserver
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema reaktor_bookingserver
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `reaktor_bookingserver` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `reaktor_bookingserver` ;

-- -----------------------------------------------------
-- Table `reaktor_bookingserver`.`constantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reaktor_bookingserver`.`constantes` (
  `clave` VARCHAR(255) NOT NULL,
  `valor` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`clave`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `reaktor_bookingserver`.`dia_semana`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reaktor_bookingserver`.`dia_semana` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `dia_semana` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `reaktor_bookingserver`.`log_reservas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reaktor_bookingserver`.`log_reservas` (
  `count_max` BIGINT NULL DEFAULT NULL,
  `fecha` DATETIME(6) NOT NULL,
  `num_registro` BIGINT NULL DEFAULT NULL,
  `accion` VARCHAR(255) NULL DEFAULT NULL,
  `loc_reserva` VARCHAR(255) NULL DEFAULT NULL,
  `recurso` VARCHAR(255) NULL DEFAULT NULL,
  `superusuario` VARCHAR(255) NULL DEFAULT NULL,
  `tipo` VARCHAR(255) NULL DEFAULT NULL,
  `usuario` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`fecha`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `reaktor_bookingserver`.`profesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reaktor_bookingserver`.`profesor` (
  `email` VARCHAR(100) NOT NULL,
  `nombre` VARCHAR(100) NULL DEFAULT NULL,
  `apellidos` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `reaktor_bookingserver`.`recurso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reaktor_bookingserver`.`recurso` (
  `bloqueado` BIT(1) NULL DEFAULT NULL,
  `cantidad` INT NULL DEFAULT NULL,
  `es_compartible` BIT(1) NULL DEFAULT NULL,
  `id` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `reaktor_bookingserver`.`tramo_horario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reaktor_bookingserver`.`tramo_horario` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `tramo_horario` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `reaktor_bookingserver`.`reserva_fija`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reaktor_bookingserver`.`reserva_fija` (
  `es_fija` BIT(1) NOT NULL,
  `n_alumnos` INT NOT NULL,
  `dia_semana_id` BIGINT NOT NULL,
  `tramo_horario_id` BIGINT NOT NULL,
  `profesor_email` VARCHAR(100) NOT NULL,
  `recurso_id` VARCHAR(150) NOT NULL,
  `motivo_curso` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`dia_semana_id`, `tramo_horario_id`, `profesor_email`, `recurso_id`),
  INDEX `FK5dn4c2wy3nndjes4m0us1d8l5` (`profesor_email` ASC) VISIBLE,
  INDEX `FKr10hg1ylfysf3oq5rnknhcl7m` (`tramo_horario_id` ASC) VISIBLE,
  INDEX `FKhcjrn2sx6dt8t2j2h0m4wqu1p` (`recurso_id` ASC) VISIBLE,
  CONSTRAINT `FK5dn4c2wy3nndjes4m0us1d8l5`
    FOREIGN KEY (`profesor_email`)
    REFERENCES `reaktor_bookingserver`.`profesor` (`email`),
  CONSTRAINT `FKhcjrn2sx6dt8t2j2h0m4wqu1p`
    FOREIGN KEY (`recurso_id`)
    REFERENCES `reaktor_bookingserver`.`recurso` (`id`),
  CONSTRAINT `FKlnur894vk89tyctu856fbu3xq`
    FOREIGN KEY (`dia_semana_id`)
    REFERENCES `reaktor_bookingserver`.`dia_semana` (`id`),
  CONSTRAINT `FKr10hg1ylfysf3oq5rnknhcl7m`
    FOREIGN KEY (`tramo_horario_id`)
    REFERENCES `reaktor_bookingserver`.`tramo_horario` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `reaktor_bookingserver`.`reserva_temporal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reaktor_bookingserver`.`reserva_temporal` (
  `es_semanal` BIT(1) NOT NULL,
  `n_alumnos` INT NOT NULL,
  `num_semana` INT NOT NULL,
  `dia_semana_id` BIGINT NOT NULL,
  `tramo_horario_id` BIGINT NOT NULL,
  `profesor_email` VARCHAR(100) NOT NULL,
  `recurso_id` VARCHAR(150) NOT NULL,
  `motivo_curso` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`num_semana`, `dia_semana_id`, `tramo_horario_id`, `profesor_email`, `recurso_id`),
  INDEX `FKaiihamg6gxtri87k571v58ngw` (`dia_semana_id` ASC) VISIBLE,
  INDEX `FKs8sqclhompmm0wdht2nodd0bg` (`profesor_email` ASC) VISIBLE,
  INDEX `FK6eik78bh0oaiyfdhwmpnwjw26` (`tramo_horario_id` ASC) VISIBLE,
  INDEX `FKlgugpu2qmmpbxs83vx2lbcoq1` (`recurso_id` ASC) VISIBLE,
  CONSTRAINT `FK6eik78bh0oaiyfdhwmpnwjw26`
    FOREIGN KEY (`tramo_horario_id`)
    REFERENCES `reaktor_bookingserver`.`tramo_horario` (`id`),
  CONSTRAINT `FKaiihamg6gxtri87k571v58ngw`
    FOREIGN KEY (`dia_semana_id`)
    REFERENCES `reaktor_bookingserver`.`dia_semana` (`id`),
  CONSTRAINT `FKlgugpu2qmmpbxs83vx2lbcoq1`
    FOREIGN KEY (`recurso_id`)
    REFERENCES `reaktor_bookingserver`.`recurso` (`id`),
  CONSTRAINT `FKs8sqclhompmm0wdht2nodd0bg`
    FOREIGN KEY (`profesor_email`)
    REFERENCES `reaktor_bookingserver`.`profesor` (`email`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
