spring:
  jpa.hibernate.ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/reaktor_bookingserver?createDatabaseIfNotExist=true
    username: root
    password: toor
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
server:
  port: 8084
  
logging:
  level:
    root: INFO
  file:
    name: C:\logs\Issues.log
    max-size: 1MB
    max-history: 10
    total-size-cap: 10MB

reaktor:
  publicKeyFile: C:\claves\public_key.pem
  urlCors: http://localhost:5173, http://192.168.1.209:5173, http://192.168.1.181:5173, http://192.168.1.137:5173, http://172.20.10.2:5173
  clientId: bookings
  constantes:
    reservasFijas: ""
    reservasTemporales: ""
    maxDiasCalendario: 60
  firebase_server_url: http://localhost:8083
  users_timeout: 30000
  http_connection_timeout: 30000
  reiniciarParametros: true